# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=2.1-mc26.2
project_group=net.frozenblock.trimpatcher
license=GPL-3.0
java_version=25

# Mod
mod_author=AViewFromTheTop/Lunade
mod_id=trimpatcher
mod_name=Trim Patcher
mod_description=Makes Armor Trims and Trim Materials from any mod work together seamlessly on all Armor items!

# Minecraft
minecraft_version=26.2
neo_form_version=26.2-1

# Fabric
fabric_loader=0.19.3
fabric_api=0.156.0+26.2
fabric_minecraft_version=>=26.2 <26.3

# NeoForge
neoforge_version=26.2.0.45-beta
neoforge_minecraft_version=[26.2, 26.3)
